site_name: Akismet for PHP
site_description: Prevent comment spam using the Akismet service, in PHP.
site_author: Cédric Belin - cedric@belin.io
site_url: https://cedx.github.io/akismet.php

docs_dir: doc
site_dir: web

repo_name: GitHub
repo_url: https://github.com/cedx/akismet.php
edit_uri: ''

copyright: Copyright &copy; 2016 - 2018 Cédric Belin
google_analytics:
- !!python/object/apply:os.getenv [GOOGLE_ANALYTICS_ID]
- auto

extra:
  social:
  - {type: globe, link: 'https://belin.io'}
  - {type: github, link: 'https://github.com/cedx'}
  - {type: twitter, link: 'https://twitter.com/cedxbelin'}
  - {type: linkedin, link: 'https://linkedin.com/in/cedxbelin'}

markdown_extensions:
- admonition
- codehilite

pages:
- Overview: index.md
- Installation: installation.md
- Usage:
  - Client setup: usage/client_setup.md
  - Data collection: usage/data_collection.md
  - Testing: usage/testing.md
  - JSON serialization: usage/json_serialization.md
  - Request lifecycle: usage/request_lifecycle.md
- Features:
  - Key verification: features/key_verification.md
  - Comment check: features/comment_check.md
  - Submit spam: features/submit_spam.md
  - Submit ham: features/submit_ham.md
- About:
  - Changelog: about/changelog.md
  - License: about/license.md
  - See also: about/see_also.md

theme:
  name: material
  favicon: img/favicon.ico
  palette: {primary: deep purple, accent: deep purple}
