site_name: Akismet for PHP
site_description: >
  Prevent comment spam using the Akismet service, in PHP.
  Add Akismet to your PHP applications so you don't have to worry about spam again.
site_author: Cédric Belin - cedric@belin.io
site_url: https://docs.belin.io/akismet.php

docs_dir: ../doc
site_dir: ../www

repo_name: git.belin.io
repo_url: https://git.belin.io/cedx/akismet.php
edit_uri: ''

copyright: Copyright &copy; 2016 - 2020 Cédric Belin
extra:
  social:
    - icon: fontawesome/solid/globe
      link: 'https://belin.io'
    - icon: fontawesome/brands/github
      link: 'https://github.com/cedx'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/cedxbelin'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/in/cedxbelin'

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Features:
      - Key verification: features/key_verification.md
      - Comment check: features/comment_check.md
      - Submit spam: features/submit_spam.md
      - Submit ham: features/submit_ham.md
  - Further reading:
      - Events: advanced/events.md
      - Testing: advanced/testing.md
  - About:
      - License: about/license.md
      - See also: about/see_also.md

theme:
  icon:
    logo: fontawesome/solid/book-reader
    repo: fontawesome/brands/git-alt
  name: material
  favicon: img/favicon.ico
  palette:
    accent: purple
    primary: purple
