name: build
on:
  - pull_request
  - push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: xdebug
          extensions: curl, intl, mbstring, simplexml
      - name: Install dependencies
        run: composer update --no-interaction
      - name: Run tests
        env:
          AKISMET_API_KEY: ${{secrets.AKISMET_API_KEY}}
        run: composer run test
      - name: Collect code coverage
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: success()
        run: composer run coverage
